### ISSUE TITLE
NORD VPN servers are out of date

### ISSUE THREAD

**Issue by Githubnub621** [sgtsquiggs/docker-deluge-openvpn#13]
Hello,

Sorry to leave such a minor issue, but I could not figure out how to solve it on my own.

The NORD VPN servers contained within the image are out of date. At first I could not get this to work with NORD VPN untill I realized that all of the Canadian (and most of the USA) servers are no longer listed on the official NORD VPN server list. When I found a USA server that was still used, I swapped to it and everything worked great (well except for the speed). 

I tried setting up NORD as a custom, following the directions and adding my best nord server as the default custom server. This worked, but my credentials (which had not changed) would not be accepted. I assume with NORD as a custom VPN there is a further issue I need to solve.

If it is not a giant issue can I get the NORD VPN server list updated? If it is a big issue, and no one uses NORD can I pass you my "best" CA server OVPN to bake into the image? If neither of those work, then just have my thanks as this is the first image I was actually able to get to work with NORD specifically. 

Thanks for everything.

**Comment by hobbitjoe** [comment]
I had the same problem as well and locally built a version to include NordVPN changes from [docker-transmission-openvpn](https://github.com/haugene/docker-transmission-openvpn/).  The changes in the upstream project uses a script to pull in openvpn files based on country code, connection type, etc instead of relying on a number of files to be in the container.

Im not sure how active this project is being maintained but ill be putting a PR up when I can and see if it can be merged in.
